/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-08-20 03:07:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    ");
 System.out.println("test"); 
      out.write("\n");
      out.write("        <!doctype html>\n");
      out.write("        <html>\n");
      out.write("\n");
      out.write("        <head>\n");
      out.write("            <meta charset=\"UTF-8\">\n");
      out.write("            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("            <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\n");
      out.write("                integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\n");
      out.write("                crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("            <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("            <script>\n");
      out.write("                tailwind.config = {\n");
      out.write("                    theme: {\n");
      out.write("                        extend: {\n");
      out.write("                            colors: {\n");
      out.write("                                clifford: '#da373d',\n");
      out.write("                                // login: '#FFCEFF'\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("            <style>\n");
      out.write("            </style>\n");
      out.write("        </head>\n");
      out.write("\n");
      out.write("        <body>\n");
      out.write("            <form action=\"signUp.jsp\" method=\"post\">\n");
      out.write("                <div class=\"container mx-auto flex flex-col h-screen\">\n");
      out.write("                    <div class=\"flex py-2 space-x-3 border border-gray-200 border-b-0\">\n");
      out.write("                        <div class=\"pl-3\">\n");
      out.write("                            <i class=\"fa-sharp-duotone fa-solid fa-bell text-xl\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <i class=\"fa-sharp-duotone fa-solid fa-barcode text-xl\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"flex-1 flex justify-center cursor-pointer\">\n");
      out.write("                            <span class=\"rounded-full p-4 hover:bg-gray-100\">\n");
      out.write("                                <i class=\"fa-sharp-duotone fa-solid fa-mug-hot text-5xl\"></i>\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <i class=\"fa-sharp-duotone fa-solid fa-magnifying-glass text-xl\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"pr-3\">\n");
      out.write("                            <i class=\"fa-sharp-duotone fa-solid fa-cart-shopping text-xl\"></i>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"border border-gray-200 py-3 border-t-0\">\n");
      out.write("                        <ul class=\"flex justify-around text-xl\">\n");
      out.write("                            <li>커피</li>\n");
      out.write("                            <li>에이드</li>\n");
      out.write("                            <li>스무디</li>\n");
      out.write("                            <li>티</li>\n");
      out.write("                            <li>디저트</li>\n");
      out.write("                            <li>MD</li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"flex-1 flex flex-col bg-gray-200 items-center justify-center\">\n");
      out.write("                        <div class=\"flex mb-10\">\n");
      out.write("                            <div class=\"flex flex-col w-80 space-y-2 mr-2\">\n");
      out.write("                                <input type=\"email\" name=\"email\" id=\"\" placeholder=\"아이디\"\n");
      out.write("                                    class=\"focus:outline-none px-2 rounded text-xl\">\n");
      out.write("                                <input type=\"password\" name=\"password\" id=\"\" placeholder=\"비밀번호\"\n");
      out.write("                                    class=\"focus:outline-none px-2 rounded text-xl\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"bg-blue-500 px-5 py-4 rounded text-2xl\">\n");
      out.write("                                <button>회원가입</button>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <div>\n");
      out.write("                                <input type=\"checkbox\" name=\"\" id=\"\">\n");
      out.write("                                <label>아이디저장하기</label>\n");
      out.write("                                <input type=\"checkbox\" name=\"\" id=\"\">\n");
      out.write("                                <label>자동 로그인</label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"relative w-96 text-center mt-10\">\n");
      out.write("                            <div class=\"border border-t-1 border-gray-400 absolute top-3 w-24\"></div>\n");
      out.write("                            간편하게 로그인하세요\n");
      out.write("                            <div class=\"border border-t-1 border-gray-400 absolute right-0 top-3 w-24\"></div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"flex space-x-3 mt-10\">\n");
      out.write("                            <a href=\"\"><img src=\"kakao.png\" alt=\"카카오\"></a>\n");
      out.write("                            <a href=\"\"><img src=\"naver.png\" alt=\"네이버\"></a>\n");
      out.write("                            <a href=\"\"><img src=\"google.png\" alt=\"구글\"></a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"relative w-96 text-center mt-10\">\n");
      out.write("                            <h1 class=\"text-2xl mb-2\">회원가입하고 적립금 5,000원 받자!</h1>\n");
      out.write("                            <h1><span>아이디 찾기</span> / <span>비밀번호 찾기</span></h1>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"border border-gray-200 py-3 border-t-0\">\n");
      out.write("                        <ul class=\"flex justify-around text-xl\">\n");
      out.write("                            <li class=\"flex flex-col items-center\">\n");
      out.write("                                <i class=\"fa-sharp-duotone fa-solid fa-house\"></i>\n");
      out.write("                                <span>HOME</span>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"flex flex-col items-center\">\n");
      out.write("                                <i class=\"fa-solid fa-hand-point-up\"></i>\n");
      out.write("                                <span>ORDER</span>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"flex flex-col items-center\">\n");
      out.write("                                <i class=\"fa-solid fa-wand-sparkles\"></i>\n");
      out.write("                                <span>EVENT</span>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"flex flex-col items-center\">\n");
      out.write("                                <i class=\"fa-solid fa-user\"></i>\n");
      out.write("                                <span>MYPAGE</span>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </body>\n");
      out.write("\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
