server:
  port: 10000

spring:
  application:
    name: ex10
  sql:
    init:
      mode: never

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/nyh
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

    defer-datasource-initialization: true

my:
  value: "welcome to my value"

