CREATE DATABASE highschool;

use highschool;

CREATE TABLE student(
S_id INTEGER AUTO_INCREMENT PRIMARY KEY,
S_name VARCHAR(20) NOT NULL,
S_year CHAR(4) NOT NULL,
S_grade VARCHAR(2) NOT NULL,
S_class VARCHAR(2) NOT NULL,
S_num VARCHAR(2) NOT NULL,
S_pass VARCHAR(20) NOT NULL DEFAULT '1234',
);

CREATE TABLE teacher(
T_id VARCHAR(15) NOT NULL PRIMARY KEY,
T_pass VARCHAR(20) NOT NULL,
T_name VARCHAR(20) NOT NULL,
T_subject VARCHAR(20) NOT NULL,
T_type INT(1) NULL DEFAULT 9
);

CREATE TABLE lesson(
L_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
L_year CHAR(4) NOT NULL,
L_semester VARCHAR(2) NOT NULL,
L_grade VARCHAR(2) NOT NULL,
L_class VARCHAR(2) NOT NULL,
L_day CHAR(1) NOT NULL,
L_time VARCHAR(2) NOT NULL,
L_room VARCHAR(20) NOT NULL,
T_id VARCHAR(15) NOT NULL,
FOREIGN KEY(T_id) REFERENCES teacher(T_id)
);

CREATE TABLE Slist(
S_id INTEGER NOT NULL,
L_id INTEGER NOT NULL,
PRIMARY KEY(L_id, S_id),
FOREIGN KEY(L_id) REFERENCES lesson(L_id),
FOREIGN KEY(S_id) REFERENCES student(S_id)
);

CREATE TABLE perform(
P_id INTEGER AUTO_INCREMENT PRIMARY KEY,
P_title VARCHAR(100) NOT NULL,
P_type CHAR(1) NULL,
P_content TINYTEXT NOT NULL,
P_line VARCHAR(100) NULL,
P_start DATE NOT NULL,
P_end DATE NOT NULL,
L_id INTEGER NOT NULL,
FOREIGN KEY(L_id) REFERENCES lesson(L_id)
);

CREATE TABLE evaluation(
S_id INTEGER NOT NULL,
P_id INTEGER NOT NULL,
E_score INTEGER NOT NULL,
E_check CHAR(1) NULL,
E_checkdate DATE NULL,
PRIMARY KEY(P_id, S_id),
FOREIGN KEY(S_id) REFERENCES student(S_id),
FOREIGN KEY(P_id) REFERENCES perform(P_id)
);